name: Build Windows Executable

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow pyinstaller
        
    - name: Build executable
      run: |
        pyinstaller --windowed --onefile --name "picboard" --icon=NONE pintu.py
        
    - name: Verify build
      run: |
        if (Test-Path "dist/picboard.exe") {
          echo "Build successful"
          dir "dist/picboard.exe"
        } else {
          echo "Build failed"
          exit 1
        }
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: picboard-windows
        path: dist/picboard.exe
        if-no-files-found: error